config/routes.rb
TestApp3::Application.routes.draw do

  resources :countries
  resources :regions
  resources :cities
  resources :turbazas

  root  'static_pages#home'

end

app/models/city.rb
class City < ActiveRecord::Base
  validates :name, presence: true
  validates :region_id, presence: true

  belongs_to :region
  has_many :turbazas
end

app/models/country.rb
class Country < ActiveRecord::Base
  validates :name, presence: true, uniqueness: {case_sensitive: false}

  has_many :regions
end

app/models/region.rb
class Region < ActiveRecord::Base
  validates :name, presence: true
  validates :country_id, presence: true

  belongs_to :country
  has_many :cities
end

app/models/turbaza.rb
class Turbaza < ActiveRecord::Base
  validates :name, presence: true
  validates :city_id, presence: true

  belongs_to :city
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def show
    @city = City.find(params[:id])
  end

  def index
    @cities = City.paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new(city_params)
    if @city.save
      redirect_to @city
    else
      render 'new'
    end
  end

  def edit
    @city = City.find(params[:id])
  end

  def update
    @city = City.find(params[:id])
    if @city.update_attributes(city_params)
      flash[:success] = "City updated"
      redirect_to @city
    else
      render 'edit'
    end
  end

  def destroy
    @city = City.find(params[:id]).destroy
    redirect_to cities_path
  end

  private

  def city_params
    params.require(:city).permit(:name, :region_id)
  end

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  def show
    @country = Country.find(params[:id])
  end

  def index
    @countries = Country.paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @country = Country.new
  end

  def create
    @country = Country.new(country_params)
    if @country.save
      redirect_to @country
    else
      render 'new'
    end
  end

  def edit
    @country = Country.find(params[:id])
  end

  def update
    @country = Country.find(params[:id])
    if @country.update_attributes(country_params)
      flash[:success] = "Country updated"
      redirect_to @country
    else
      render 'edit'
    end
  end

  def destroy
    @country = Country.find(params[:id]).destroy
    redirect_to countries_path
  end

  private

  def country_params
    params.require(:country).permit(:name)
  end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController

  def show
    @region = Region.find(params[:id])
  end

  def index
    @regions = Region.paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @region = Region.new
  end

  def create
    @region = Region.new(region_params)
    if @region.save
      redirect_to @region
    else
      render 'new'
    end
  end

  def edit
    @region = Region.find(params[:id])
  end

  def update
    @region = Region.find(params[:id])
    if @region.update_attributes(region_params)
      flash[:success] = "Region updated"
      redirect_to @region
    else
      render 'edit'
    end
  end

  def destroy
    @region = Region.find(params[:id]).destroy
    redirect_to regions_path
  end

  private

  def region_params
    params.require(:region).permit(:name, :country_id)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @countries = Country.all
  end
end

app/controllers/turbazas_controller.rb
class TurbazasController < ApplicationController

  def show
    @turbaza = Turbaza.find(params[:id])
  end

  def index
    @turbazas = Turbaza.paginate(:page => params[:page], :per_page => 10)
    @countries = Country.all
  end

  def new
    @turbaza = Turbaza.new
  end

  def create
    @turbaza = Turbaza.new(turbaza_params)
    if @turbaza.save
      redirect_to @turbaza
    else
      render 'new'
    end
  end

  def edit
    @turbaza = Turbaza.find(params[:id])
  end

  def update
    @turbaza = Turbaza.find(params[:id])
    if @turbaza.update_attributes(turbaza_params)
      flash[:success] = "Turbaza updated"
      redirect_to @turbaza
    else
      render 'edit'
    end
  end

  def destroy
    @turbaza = Turbaza.find(params[:id]).destroy
    redirect_to turbazas_path
  end

  private

  def turbaza_params
    params.require(:turbaza).permit(:name, :city_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/turbazas_helper.rb
module TurbazasHelper
end

app/views/cities/edit.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@city) do |f| %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :region_id %>
        <%= f.text_field :region_id %>

        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/cities/index.html.erb
<h1>List of cities</h1>

<button class="btn btn-default">
  <%= link_to "Add", new_city_path %>
</button>

<table>
  <tr>
    <th>id</th>
    <th>name</th>
    <th>region name</th>
  </tr>
  <% @cities.each do|city| %>
      <tr>
        <td>
          <%= city.id %>
        </td>
        <td>
          <%= city.name %>
        </td>
        <td><%if city.region_id == 0 %>
              <%= Region.find(city.region_id + 1).name %>
          <% else %>
              <%= Region.find(city.region_id).name %>
          <% end %>
        </td>
        <td>
          <%= link_to "Edit", edit_city_path(city) %>
        </td>
        <td>
          <%= link_to "Delete", city, method: :delete %>
        </td>
  <% end %>
  </tr>
</table>

<%= will_paginate @cities%>

app/views/cities/new.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@city) do |f| %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :region_id %>
        <%= f.text_field :region_id %>

        <%= f.submit "Create new city", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/cities/show.html.erb
<% provide(:title, @city.name) %>
<h1><%= @city.name %></h1>

<div class="row">
  <div class="col-md-12">
    <div class="col-md-4">
      <button class="btn btn-default">
        <%= link_to "Back to all cities", cities_path %>
      </button>
    </div>
    <div class="col-md-4">
      <button class="btn btn-default">
        <%= link_to "Edit", edit_city_path %>
      </button>
    </div>
    <div class="col-md-4">
      <button class="btn btn-default">
        <%= link_to "Delete", city_path, method: :delete %>
      </button>
    </div>
  </div>
</div>

app/views/countries/edit.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@country) do |f| %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/countries/index.html.erb
<h1>List of countries</h1>

<button class="btn btn-default">
  <%= link_to "Add", new_country_path %>
</button>

<table>
  <tr>
    <th>id</th>
    <th>name</th>
  </tr>
  <% @countries.each do|country| %>
      <tr>
        <td>
          <%= country.id %>
        </td>
        <td>
          <%= country.name %>
        </td>
        <td>
          <%= link_to "Edit", edit_country_path(country) %>
        </td>
        <td>
          <%= link_to "Delete", country, method: :delete %>
        </td>
  <% end %>
  </tr>
</table>

<%= will_paginate @countries %>

app/views/countries/new.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@country) do |f| %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.submit "Create new country", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/countries/show.html.erb
<% provide(:title, @country.name) %>
<h1><%= @country.name %></h1>

<div class="row">
  <div class="col-md-12">
    <div class="col-md-4">
      <button class="btn btn-default">
        <%= link_to "Back to all countries", countries_path %>
      </button>
    </div>
    <div class="col-md-4">
      <button class="btn btn-default">
        <%= link_to "Edit", edit_country_path %>
      </button>
    </div>
    <div class="col-md-4">
      <button class="btn btn-default">
        <%= link_to "Delete", country_path, method: :delete %>
      </button>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "custom" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

  <header>
    <div class="col-md-12 no-padding">
      <div class="col-md-6">
        <%= link_to "Main", root_path %>
      </div>
      <div class="col-md-6 text-right">
        <div class="col-md-3">
          <%= link_to "Countries", countries_path %>
        </div>
        <div class="col-md-3">
          <%= link_to "Regions", regions_path %>
        </div>
        <div class="col-md-3">
          <%= link_to "Cities", cities_path %>
        </div>
        <div class="col-md-3">
          <%= link_to "Turbazas", turbazas_path %>
        </div>
      </div>
    </div>
  </header>
</div>
<div class="container">
  <%= yield %>
</div>


</body>
</html>

app/views/regions/edit.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@region) do |f| %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :nacountry_idme %>
        <%= f.text_field :country_id %>

        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/regions/index.html.erb
<h1>List of regions</h1>

<button class="btn btn-default">
  <%= link_to "Add", new_region_path %>
</button>

<table>
  <tr>
    <th>id</th>
    <th>name</th>
    <th>country name</th>
  </tr>
  <% @regions.each do|region| %>
      <tr>
        <td>
          <%= region.id %>
        </td>
        <td>
          <%= region.name %>
        </td>
        <td>
          <%if region.country_id == 0 %>
              <%= Country.find(region.country_id + 1).name %>
          <% else %>
              <%= Country.find(region.country_id).name %>
          <% end %>
        </td>
        <td>
          <%= link_to "Edit", edit_region_path(region) %>
        </td>
        <td>
          <%= link_to "Delete", region, method: :delete %>
        </td>
  <% end %>
  </tr>
</table>

<%= will_paginate @regions%>

app/views/regions/new.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@region) do |f| %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :country_id %>
        <%= f.text_field :country_id %>

        <%= f.submit "Create new region", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/regions/show.html.erb
<% provide(:title, @region.name) %>
<h1><%= @region.name %></h1>

<div class="row">
  <div class="col-md-12">
    <div class="col-md-4">
      <button class="btn btn-default">
        <%= link_to "Back to all regions", regions_path %>
      </button>
    </div>
    <div class="col-md-4">
      <button class="btn btn-default">
        <%= link_to "Edit", edit_region_path %>
      </button>
    </div>
    <div class="col-md-4">
      <button class="btn btn-default">
        <%= link_to "Delete", region_path, method: :delete %>
      </button>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<h1>Quantity of turbazas</h1>
<% tmp_country = 0 %>
<% @countries.each do|country| %>
    <div class="col-md-3">
    <% tmp_2 = 0 %>
    <% tmp = 0 %>
    <% country.regions.each do|region| %>
        <% turbaza_in_region = 0 %>
        <% region.cities.each do|city| %>
            <%= city.name %> <%='(' + city.turbazas.count.to_s + ')' %>
            <% tmp += city.turbazas.count %>
        <% end %>
        <% turbaza_in_region += tmp %>
        <%= region.name %> <%= '(' + turbaza_in_region.to_s + ')' %>
        <% tmp_2 += turbaza_in_region %>
    <% end %>
    <% tmp_country += tmp_2 %>
    <%= country.name %> <%= '(' + tmp_country.to_s + ')' %>
    </div>
<% end %>

app/views/turbazas/edit.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@turbaza) do |f| %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :city_id %>
        <%= f.text_field :city_id %>

        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/turbazas/index.html.erb
<h1>List of turbazas</h1>

<button class="btn btn-default">
  <%= link_to "Add", new_turbaza_path %>
</button>

<table>
  <tr>
    <th>id</th>
    <th>name</th>
    <th>city name</th>
  </tr>
  <% @turbazas.each do|turbaza| %>
      <tr>
        <td>
          <%= turbaza.id %>
        </td>
        <td>
          <%= turbaza.name %>
        </td>
        <td>
          <%if turbaza.city_id == 0 %>
              <%= City.find(turbaza.city_id + 1).name %>
          <% else %>
              <%= City.find(turbaza.city_id).name %>
          <% end %>
        </td>
        <td>
          <%= link_to "Edit", edit_turbaza_path(turbaza) %>
        </td>
        <td>
          <%= link_to "Delete", turbaza, method: :delete %>
        </td>
  <% end %>
  </tr>
</table>


<%= will_paginate @turbazas%>

app/views/turbazas/new.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@turbaza) do |f| %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :city_id %>
        <%= f.text_field :city_id %>

        <%= f.submit "Create new turbaza", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/turbazas/show.html.erb
<% provide(:title, @turbaza.name) %>
<h1><%= @turbaza.name %></h1>

<div class="row">
  <div class="col-md-12">
    <div class="col-md-4">
      <button class="btn btn-default">
        <%= link_to "Back to all cities", turbazas_path %>
      </button>
    </div>
    <div class="col-md-4">
      <button class="btn btn-default">
        <%= link_to "Edit", edit_turbaza_path %>
      </button>
    </div>
    <div class="col-md-4">
      <button class="btn btn-default">
        <%= link_to "Delete", turbaza_path, method: :delete %>
      </button>
    </div>
  </div>
</div>